security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: username
    
    role_hierarchy:
        ROLE_ADMIN:        [ROLE_PAGE1, ROLE_PAGE2]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            provider: db_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
                    
    
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/page/1, roles: ROLE_PAGE1 }
        - { path: ^/page/2, roles: ROLE_PAGE2 }
